version: 2
jobs:
  build:
    working_directory: /ballparkscraping
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run ballparkscraping go run main.go