version: 2
jobs:
  build:
    working_directory: /go/src/github.com/johnliu8365/BallparkScraping
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run ballparkscraping go run main.go
      - deploy:
        name: Push application Docker image
        command: |
          docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
          docker tag ballparkscraping $DOCKER_HUB_USER_ID/BallparkScraping:$CIRCLE_SHA1
          docker tag ballparkscraping $DOCKER_HUB_USER_ID/BallparkScraping:latest
          docker push $DOCKER_HUB_USER_ID/BallparkScraping:$CIRCLE_SHA1
          docker push $DOCKER_HUB_USER_ID/BallparkScraping:latest